name: pet_home
description: adoption app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^7.0.1
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  google_fonts: ^6.1.0
  flutter_custom_clippers: ^2.1.0
  dropdown_search: ^5.0.6
  dio: ^5.4.1
  equatable: ^2.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  hooks_riverpod: ^2.4.10
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  url_strategy: ^0.2.0
  jwt_decoder: ^2.0.1
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/animations/

  fonts:
    - family: PetHome
      fonts:
        - asset: assets/icons/Pethome.ttf
